const seedProducts = [
  {
    name: "Standard Thali",
    description: "Dal, sabzi, rice, roti, salad, and pickle — a complete homely meal.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&auto=format&fit=crop",
    price: 120,
    status: "AVAILABLE",
    category: "THALI",
  },
  {
    name: "Deluxe Thali",
    description: "Premium thali with paneer sabzi, jeera rice, butter roti, raita, and dessert.",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&auto=format&fit=crop",
    price: 180,
    status: "AVAILABLE",
    category: "THALI",
  },
  {
    name: "Rajma Rice Combo",
    description: "Slow-cooked rajma with steamed rice and onion salad.",
    image: "https://images.unsplash.com/photo-1516684669130-aa58539042e5?w=400&auto=format&fit=crop",
    price: 99,
    status: "AVAILABLE",
    category: "COMBO_MEAL",
  },
  {
    name: "Chole Rice Combo",
    description: "Spiced chickpea curry served with fragrant basmati rice.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&auto=format&fit=crop",
    price: 99,
    status: "AVAILABLE",
    category: "COMBO_MEAL",
  },
  {
    name: "Extra Roti",
    description: "Fresh whole wheat roti prepared on order.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&auto=format&fit=crop",
    price: 15,
    status: "AVAILABLE",
    category: "ADD_ON",
  },
  {
    name: "Garden Salad",
    description: "Crisp cucumber, tomato, onion, and lemon dressing.",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop",
    price: 40,
    status: "AVAILABLE",
    category: "ADD_ON",
  },
  {
    name: "Boondi Raita",
    description: "Cool yogurt raita with boondi and roasted cumin.",
    image: "https://images.unsplash.com/photo-1631452181589-215fdab553a8?w=400&auto=format&fit=crop",
    price: 35,
    status: "AVAILABLE",
    category: "ADD_ON",
  },
];

module.exports = seedProducts;
